In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
np.__version__

'1.19.5'

**Vector 0r 1D array
**

In [8]:
a = np.array([1,2,3,4,5,6,7])
a


array([1, 2, 3, 4, 5, 6, 7])

Matrix or 2D array

In [10]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a = np.array([1,2,3,4,5,6,7])
a[0]

1

In [12]:
a[2:5]

array([3, 4, 5])

In [13]:
L = [1,2,3,4,5,6,7]
L[0]

1

In [14]:
L[2:5]

[3, 4, 5]

In [15]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [16]:
L[:6]

[1, 2, 3, 4, 5, 6]

In [17]:
a[3:]

array([4, 5, 6, 7])

In [19]:
L[3:]

[4, 5, 6, 7]

In [23]:
a[-1]

7

In [24]:
a[-2]

6

In [25]:
L[-1]

7

In [26]:
a[2:-3]

array([3, 4])

In [28]:
a[-5:]

array([3, 4, 5, 6, 7])

In [29]:
a[-5:-1]

array([3, 4, 5, 6])

In [30]:
a[-2:2]

array([], dtype=int64)

In [31]:
np.size(a)

7

In [32]:
np.shape(a)

(7,)

In [33]:
a[a[2]]

4

array reverse ไม่ได้

In [35]:
L.reverse()
L

[1, 2, 3, 4, 5, 6, 7]

In [45]:
sorted(a, reverse =True)

[7, 6, 5, 4, 3, 2, 1]

In [46]:
a.reshape(1,7)
np.shape(a)

(7,)

In [47]:
a


array([1, 2, 3, 4, 5, 6, 7])

In [50]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
L = [[1,2,3],[4,5,6],[7,8,9]]
L

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [52]:
a[0,0]

1

In [55]:
L[0][0]

1

In [56]:
a[1,:]

array([4, 5, 6])

In [58]:
L[1][:]

[4, 5, 6]

In [59]:
a[:,-1]

array([3, 6, 9])

In [60]:
a[:,2]

array([3, 6, 9])

incorrect

In [61]:
L[:][-1]

[7, 8, 9]

In [62]:
a[:,1] = 0
a

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])

In [63]:
a[0:2,:] = 8
a

array([[8, 8, 8],
       [8, 8, 8],
       [7, 0, 9]])

In [79]:
a[0:3,-1] = 5
a

array([[8, 8, 5],
       [8, 8, 5],
       [7, 0, 5]])

In [64]:
a.shape

(3, 3)

In [65]:
a.size

9

In [66]:
np.size(a,1)



3

In [67]:
np.ndim(a)


2

In [80]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [83]:
np_mix_matrix[:,1]

array(['2', '4', '6'], dtype='<U5')

In [82]:
np.array(np_mix_matrix[:,1], dtype=int)

array([2, 4, 6])

In [100]:
c = np.zeros((5,3))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [98]:
c = np.ones((10))
c

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [97]:
c = np.ones((4,4))
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [95]:
c = np.ones((5,5))*8
c

array([[8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8.]])

In [102]:
c = np.full((2,2),8)
c

array([[8, 8],
       [8, 8]])

In [94]:
d = np.eye(5,5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [103]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [104]:
c*d

array([[8., 0.],
       [0., 8.]])

In [105]:
np.matmul(c,d)

array([[8., 8.],
       [8., 8.]])

In [106]:
np.sqrt(np.ones((5,5))*9)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [113]:
np.empty((8,8))

array([[4.66367635e-310, 0.00000000e+000,             nan,
        6.01390857e-154, 0.00000000e+000, 4.66367371e-310,
        7.41098469e-323, 4.66367635e-310],
       [6.90878804e-310, 6.90878901e-310, 6.90878804e-310,
        0.00000000e+000, 4.66367636e-310, 0.00000000e+000,
        0.00000000e+000, 6.60925308e-062],
       [0.00000000e+000, 6.13256784e-312, 9.02110782e+217,
        1.15645537e-176, 6.60925309e-062, 1.44062231e-176,
        2.19844283e+256, 7.52887706e+130],
       [3.06370797e-057, 7.60446783e+130, 9.36407150e-076,
        1.11416848e+218, 9.02133865e+217, 1.00385544e+218,
        1.24766176e-177, 6.01347002e-154],
       [1.55743982e+243, 9.36407805e-076, 8.60088618e-177,
        6.60925309e-062, 7.60446783e+130, 9.36407150e-076,
        2.00819421e-178, 2.82885492e+276],
       [1.81975827e-176, 4.99186928e+223, 5.29874766e+180,
        6.54464569e-072, 1.02189773e-152, 6.32275266e+233,
        6.90878639e-310, 7.16395186e-322],
       [6.90878837e-310, 0.0000000

In [119]:
c = np.ones((5,3))*9
c

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

In [122]:
np.power(c,2)

array([[81., 81., 81.],
       [81., 81., 81.],
       [81., 81., 81.],
       [81., 81., 81.],
       [81., 81., 81.]])

In [123]:
def addone(a):
    return a+1

เลขที่สุ่มออกมาจะอยู่ในช่วง 0-1

In [213]:
rng = np.random.RandomState(0)
rng.rand()

0.5488135039273248

In [227]:
rng = np.random.RandomState(0)
rng.random()*10


5.4881350392732475

In [234]:
rng = np.random.RandomState(0)
[np.round(np.random.rand()*10)for item in range(10)]

[5.0, 6.0, 2.0, 1.0, 0.0, 4.0, 7.0, 4.0, 4.0, 4.0]

In [235]:
np.random.randint(5)

0

In [151]:
np.random.seed = 0
[np.random.randint(5) for item in range(10)]

[3, 4, 2, 2, 3, 0, 2, 4, 0, 2]

In [146]:
np.random.rand(5,5)


array([[0.35378475, 0.29193088, 0.66874653, 0.29891275, 0.69992944],
       [0.77813796, 0.73560906, 0.13582067, 0.71456755, 0.21472589],
       [0.52065651, 0.31709942, 0.11313143, 0.7158927 , 0.56915559],
       [0.8488267 , 0.74469675, 0.56172858, 0.39667682, 0.24343935],
       [0.9803534 , 0.34683562, 0.32855935, 0.46350792, 0.24225808]])

In [106]:
np.sqrt(np.ones((5,5))*9)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [106]:
np.sqrt(np.ones((5,5))*9)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [106]:
np.sqrt(np.ones((5,5))*9)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

มีเลขซ้ำ

In [153]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([4, 7, 2, 7, 2])

ไม่ซ้ำ

In [158]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace = False)

array([2, 7, 5, 3, 6])

In [164]:
np_matrix = np.round(np.random.rand(1000,5))
np_matrix

array([[0., 0., 1., 1., 0.],
       [0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0.],
       ...,
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 0.]])

In [165]:
idx_choose = np.random.choice(1000,100, replace = False)
idx_choose

array([937, 812, 476, 517, 965, 848,  31, 738, 406, 933, 135, 835, 762,
       446, 839, 691, 332, 196, 359, 900, 487, 915, 741, 567, 456, 506,
       585, 957, 533, 105, 455,  59,  13, 664, 553, 783, 859, 706, 752,
       723, 565, 308, 924, 575, 497, 908, 231, 507, 316, 994, 846,  21,
       202, 324, 176, 841, 434,  64, 326, 874, 548, 588, 503, 554, 102,
       363, 944, 295, 732, 981, 410, 695,  33, 277,  39, 748, 449, 213,
        57, 926, 779, 597,  40, 283, 592, 124, 120, 121, 477, 663, 549,
         9, 328, 276,  15, 260, 866,  28, 312, 556])

In [180]:
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[0.27800999, 0.55104264, 0.98881927, 0.32838937, 0.69710646],
       [0.78457957, 0.26334281, 0.04853689, 0.80804277, 0.69474975],
       [0.71864608, 0.95126644, 0.84999694, 0.3818586 , 0.14949331]])

In [184]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[0, 1, 1, 0, 0],
       [1, 0, 1, 0, 0],
       [1, 1, 1, 1, 2],
       [1, 1, 2, 2, 1],
       [0, 0, 2, 1, 1]])

In [186]:
i,j = np.where(np_matrix == 2)
[(i[ii],j[ii]) for ii in range (len(i))]

[(2, 4), (3, 2), (3, 3), (4, 2)]

In [265]:
rng = np.random.RandomState(0)
rp_matrix = rng.randint(3,size = (4,4))
rp_matrix

array([[0, 1, 0, 1],
       [1, 2, 0, 2],
       [0, 0, 0, 2],
       [1, 2, 2, 0]])

# ****ข้อสอง


In [383]:
rp_matrix = np.random.rand(10,5)
rp_matrix[:,-1] = np.round(rp_matrix[:,-1])
rp_matrix




array([[0.52863098, 0.4667243 , 0.80504911, 0.50449497, 0.        ],
       [0.37916236, 0.87892722, 0.90711941, 0.9574445 , 0.        ],
       [0.59398046, 0.20687123, 0.41437086, 0.21827899, 0.        ],
       [0.96989514, 0.21838932, 0.30858396, 0.07679052, 0.        ],
       [0.32600692, 0.13541414, 0.43722899, 0.53937347, 0.        ],
       [0.02402591, 0.40369807, 0.52211291, 0.78454895, 0.        ],
       [0.1093592 , 0.89660929, 0.27178668, 0.31783354, 0.        ],
       [0.15409582, 0.66846821, 0.23524881, 0.1265081 , 1.        ],
       [0.26208717, 0.47140081, 0.91230967, 0.45208643, 0.        ],
       [0.11231803, 0.6969056 , 0.05811174, 0.61692609, 1.        ]])

# ****ข้อสาม



In [391]:
#เพราะใน array มีแค่ข้อมูลแค่ 4 ข้อมูล
idx = [1,2,3,4,5]
np_matrix[len(idx)-1,:]
idx


[1, 2, 3, 4, 5]

# ****ข้อสี่

data matrix

In [405]:
matrix = np.random.randint(10, size = (10,5))
matrix





array([[0, 5, 4, 6, 7],
       [1, 1, 0, 8, 8],
       [4, 9, 1, 5, 1],
       [9, 5, 8, 7, 9],
       [0, 9, 0, 3, 9],
       [5, 7, 6, 7, 0],
       [3, 9, 6, 1, 1],
       [7, 9, 0, 9, 2],
       [4, 3, 9, 8, 4],
       [3, 5, 0, 4, 2]])

label vector

In [406]:
group = np.random.randint(2, size = 10)
group

array([1, 0, 0, 0, 1, 1, 0, 1, 0, 0])

In [407]:
matrix[np.where(group == 0)]

array([[1, 1, 0, 8, 8],
       [4, 9, 1, 5, 1],
       [9, 5, 8, 7, 9],
       [3, 9, 6, 1, 1],
       [4, 3, 9, 8, 4],
       [3, 5, 0, 4, 2]])

In [408]:
matrix[np.where(group == 1)]

array([[0, 5, 4, 6, 7],
       [0, 9, 0, 3, 9],
       [5, 7, 6, 7, 0],
       [7, 9, 0, 9, 2]])